---
version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang:1.15

    working_directory: /go/src/github.com/FundingCircle/haproxy_exporter
    steps:
    - checkout
    - run: make

workflows:
  version: 2
  haproxy_exporter:
    jobs:
    - test
