---
version: 2.1

jobs:
  test:
    docker:
    - image: circleci/golang:1.12

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
    - checkout
    - run: make

workflows:
  version: 2
  haproxy_exporter:
    jobs:
    - test
